### ISSUE TITLE
orientformat 2 matrix hierarchical (not supported)

### ISSUE THREAD

**Issue by jeremybailey** [diablodale/dp.kinect2#13]
Confused why I can't seem to select orientformat 2 matrix hierarchical, it says (not supported)

"matrix hierarchical (not supported)"

would really love my data in this format instead of quats.
is this a known issue?

**Comment by diablodale** [comment]
It is...not supported.  ;-)
Microsoft dropped that feature on the Kinectv2 SDK.
Because of the very low need, I did not implement it by hand myself.
It is possible for you to calculate these yourself using the hierarchy of joints + the quaternion hierarchical values dp.kinect2 provides. And max has objects, like jit.anim.node, which can accept the quat hierarchical rotations...they can even output matrices if you want them.

**Comment by diablodale** [comment]
Hello. I added a full suite of joint orientation data to dp.kinect2. You can test it with the v1.1 beta from the usual download location http://hidale.com/shop/dp-kinect2/
