### ISSUE TITLE
Align color to depth causes a shadowed color image

### ISSUE THREAD

**Issue by gavspav** [diablodale/dp.kinect2#3]
I have a Desktop PC running 8.1 64 bit. GTX 860, i5 4690K, 8GB Ram, Z87X D3H
Max 6.1.8 32bit running the month demo

Just using the dpkinect2 demo/help patch, if I select align 1.color to depth, I get a weird ghosting of the color image. This is something to do with the inaccuracy of the alignment close to the camera but I don't really get what is happening here.

**Comment by lwoodbury** [comment]
I was going to report this, but it looks like you are saying this is expected functionality. I just wanted to ask why this isn't an issue with dp.kinect? I understand that the resolutions match as one is half the other, but they are still out of line aren't they? How come the aligned colour image does not have these black edge and double image artefacts?

![with align](https://cloud.githubusercontent.com/assets/1011373/6137326/e191739e-b16f-11e4-9746-238db396a938.PNG)

**Comment by diablodale** [comment]
It is a behavior also with the Kinect v1 (all apps). In the color picture above you attach I do see the same problems. There are unmappable (usually rendered as black) pixels in bulk on the left and top and bottom. There are unmappable black pixels along the edges of objects like the file cabinet, vents/ducts above, etc.  If you were to put your hadn extremely close to the Kinect v1 (and off center for most affect) you will see a duplicate of the topmost Kinectv2 image. The color and depth cameras can not occupy the same physical space, therefore they will not have the same viewpoint and therefore can not always map data equally.
There isn't anything wrong. Its expected and part of the process/method inherit in current depth/color camera technologies.

**Comment by lwoodbury** [comment]
Apologies, you are right, it does happen to some extent with dp.kinect1 as well (the previous screenshot was v2, this one is v1). It doesn't seem to be very apparent around the user like it is with v2 and the double image thing doesn't happen. In the v2 one you can see the doubling on my back and the back of my head whereas I can't pick out anything like that with the v1 image, but there are still some black lines around background equipment which doesn't show up too well in this picture. 

![dp kinect1](https://cloud.githubusercontent.com/assets/1011373/6210677/dccdd984-b5c9-11e4-975a-e7da32f4c325.PNG)

**Comment by diablodale** [comment]
Attached here is a screenshot of dp.kinect using the original Kinect. On the left you can see the two outlines of my hand in the depthmap and on the right the duplicated rgb image of my hand. This is expected behavior and matches much of what you see in the Kinect v2.
![k1](https://cloud.githubusercontent.com/assets/679350/6212660/251c1322-b5e8-11e4-88d3-81035c3e306c.png)

**Comment by lwoodbury** [comment]
OK, I guess in my current use (green screening) v1 has been a lot more forgiving and I didn't even notice it as an issue, but with v2 it has become very obvious and there are thick black lines all around the user and some obvious doubling. However, I understand that you are saying this is not an issue with your implementation and something inherent in the way the sensor works. Thanks for the help.

**Comment by mrmaarten** [comment]
Hi, I would to chime in: with dp.kinect1 and the beta of dp.kinect2 I have had no issue aligning the depthmap (filtered on distance and with 100% contrast) to the colormap and with a jit.pack I could create a good key. 

example: https://vimeo.com/119710704

I never used @align 1 because this would always create the black in the colormap, as described above.

With the beta (I am not sure I ever used dp.kinect2 1.0) of dp.kinectv2 I would scale the filtered depthmap up to 1304x1080 and I would crop the colormap by 308pixels on either side. jit.pack-ing this together would create a fine key. Unfortunately now not anymore! 

Now the depthmap and colormap dont align anymore and when I offset it depends a lot on the distance. I get the explanation, but to my idea it was working pretty well before. 

Could you maybe verify that is was working in the beta before release? Thanks!

**Comment by diablodale** [comment]
It is rarely reliable to do aligning with your method (scale, crop, etc.) that you write. Every Kinect hardware has a different lens and sensor alignment. In addition, the specific pixels which should be aligned change based on distance and angle to the Kinect.

Only the use of @align will create consistent reliable alignment across all Kinects and all scenes.
A combination of @align and the playermap (or @depthonlyplayers) can create something similar to a greenscreen affect. A version of dp.kinect2 currently in testing allows for aligning the depth->color image which enables you to retain the higher resolution of the color image.

**Comment by mrmaarten** [comment]
Yeah I get what you are saying. And in with dp.kinectv1 I didn't apply scaling or cropping, and it works really well. (as seen in the video my method works pretty well: the offset is minimal in a wide variety of distances. I applied a blur to the mask, for aesthetic reasons and that creates even the most offset because of a slight delay in processing.)

And I understand that the Kinectv2 hardware is different from the Kinectv2, but in the last beta it also worked fine (with cropping).But I cannot test it anymore because the beta's don't work anymore. 

I  just mention it for reference/ data points. But it sounds that your version of aligned depthmap will work well and I am looking very much forward to it.
